### ISSUE TITLE
Chinese characters are not rendering

### ISSUE THREAD

**Issue by ghost** [boramalper/cecibot#1]
Send URL to the bot on telegram. 
If(webLang === English){
return fileWithoutImage;
} else if(webLang === Chinese){
return fileWithErrorCode;
}
URL 1: https://www.bbc.com
URL 2: https://cn.nytimes.com 
![image](https://user-images.githubusercontent.com/32025115/38207082-2c25defc-36df-11e8-87a6-6ca8415d3fb6.png)
![image](https://user-images.githubusercontent.com/32025115/38207108-411eae60-36df-11e8-80e1-bf7892bcc197.png)

**Comment by boramalper** [comment]
Fixed, thanks for the heads up!
